---
- name: check if dsa file exist
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    myfile: 'C:\Program Files\Trend Micro\Deep Security Agent\dsa_query.cmd'
  tasks:
    - name: check if DSA file exist
      ansible.windows.win_stat:
        path: "{{ myfile }}"
      register: file_data
    - name: dsa file exist
      ansible.builtin.debug:
        msg: "The file {{ myfile }} exist"
      when: file_data.stat.exists
    - name: dsa file not exist
      ansible.builtin.debug:
        msg: "The file {{ myfile }} doesn't exist"
      when: not file_data.stat.exists