# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Activate the Deep Security Agent (For Linux only)
# *********************************************************************
---
- name: Check if CyberEye Sever Agent file exist - Windows Only
  hosts: windows

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
# *********************************************************************
# * Check if DSA installed properly
# *********************************************************************
    - debug:
        msg: "Checking if CyberEye ServerSec Agent installed properly."

    - stat:
        path: 'C:\Program Files\Trend Micro\Deep Security Agent\dsa_query.cmd'
      register: dsaQuery

    - name: CyberEye ServerSec Agent installed
      debug:
        msg: "CyberEye ServerSec Agent already installed "
      when: dsaQuery.stat.exists

    - fail:
        msg: "Could not find CyberEye ServerSec Agent on this host."
      when: dsaQuery.stat.exists != true
